name: Deploy to Firebase Hosting on Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Build Flutter web app
        run: flutter build web

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FINALPROJECT_C4F50 }}
        run: firebase deploy --only hosting
